CRITICAL - 2025-05-09 01:35:39 --> CodeIgniter\Exceptions\ConfigException: Config\App::$baseURL "/" is not a valid URL.
in SYSTEMPATH\HTTP\SiteURI.php on line 199.
 1 SYSTEMPATH\HTTP\SiteURI.php(145): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
 2 SYSTEMPATH\HTTP\SiteURI.php(100): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), null, null)
 3 SYSTEMPATH\HTTP\SiteURIFactory.php(224): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), '/', null)
 4 SYSTEMPATH\HTTP\SiteURIFactory.php(45): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('/')
 5 SYSTEMPATH\Config\Services.php(805): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
 6 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(null, false)
 7 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', [...])
 8 SYSTEMPATH\Config\Services.php(798): CodeIgniter\Config\BaseService::getSharedInstance('uri', null)
 9 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
10 SYSTEMPATH\Config\Services.php(566): CodeIgniter\Config\BaseService::__callStatic('uri', [])
11 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
12 SYSTEMPATH\Config\Services.php(524): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', [...])
13 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::request(Object(Config\App), false)
14 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', [...])
15 SYSTEMPATH\Config\Services.php(559): CodeIgniter\Config\BaseService::getSharedInstance('request', Object(Config\App))
16 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App))
17 SYSTEMPATH\Config\Services.php(539): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', [...])
18 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::createRequest(Object(Config\App))
19 SYSTEMPATH\CodeIgniter.php(656): CodeIgniter\Config\BaseService::__callStatic('createRequest', [...])
20 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->getRequestObject()
21 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-05-09 01:35:39 --> ErrorException: Uncaught CodeIgniter\Exceptions\ConfigException: Config\App::$baseURL "/" is not a valid URL. in C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\HTTP\SiteURI.php:199
Stack trace:
#0 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\HTTP\SiteURI.php(145): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
#1 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\HTTP\SiteURI.php(100): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), NULL, NULL)
#2 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\HTTP\SiteURIFactory.php(224): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), '/', NULL)
#3 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\HTTP\SiteURIFactory.php(45): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('/')
#4 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(805): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
#5 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(NULL, false)
#6 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#7 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(798): CodeIgniter\Config\BaseService::getSharedInstance('uri', NULL)
#8 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
#9 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(566): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#10 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
#11 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(524): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', Array)
#12 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request(NULL, false)
#13 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#14 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(520): CodeIgniter\Config\BaseService::getSharedInstance('request', NULL)
#15 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request()
#16 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Debug\Exceptions.php(150): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#17 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\ConfigException))
#18 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\ConfigException
Config\App::$baseURL "/" is not a valid URL.
#0 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\HTTP\SiteURI.php(145): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
#1 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\HTTP\SiteURI.php(100): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), NULL, NULL)
#2 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\HTTP\SiteURIFactory.php(224): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), '/', NULL)
#3 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\HTTP\SiteURIFactory.php(45): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('/')
#4 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(805): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
#5 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(NULL, false)
#6 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#7 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(798): CodeIgniter\Config\BaseService::getSharedInstance('uri', NULL)
#8 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
#9 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(566): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#10 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
#11 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(524): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', Array)
#12 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request(Object(Config\App), false)
#13 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#14 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(559): CodeIgniter\Config\BaseService::getSharedInstance('request', Object(Config\App))
#15 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App))
#16 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(539): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', Array)
#17 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::createRequest(Object(Config\App))
#18 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(656): CodeIgniter\Config\BaseService::__callStatic('createRequest', Array)
#19 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->getRequestObject()
#20 C:\xampp\htdocs\inventory_system\index.php(79): CodeIgniter\CodeIgniter->run()
#21 {main}
in SYSTEMPATH\HTTP\SiteURI.php on line 199.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2025-05-09 01:35:45 --> CodeIgniter\Exceptions\ConfigException: Config\App::$baseURL "/" is not a valid URL.
in SYSTEMPATH\HTTP\SiteURI.php on line 199.
 1 SYSTEMPATH\HTTP\SiteURI.php(145): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
 2 SYSTEMPATH\HTTP\SiteURI.php(100): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), null, null)
 3 SYSTEMPATH\HTTP\SiteURIFactory.php(224): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), '/', null)
 4 SYSTEMPATH\HTTP\SiteURIFactory.php(45): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('/')
 5 SYSTEMPATH\Config\Services.php(805): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
 6 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(null, false)
 7 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', [...])
 8 SYSTEMPATH\Config\Services.php(798): CodeIgniter\Config\BaseService::getSharedInstance('uri', null)
 9 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
10 SYSTEMPATH\Config\Services.php(566): CodeIgniter\Config\BaseService::__callStatic('uri', [])
11 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
12 SYSTEMPATH\Config\Services.php(524): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', [...])
13 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::request(Object(Config\App), false)
14 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', [...])
15 SYSTEMPATH\Config\Services.php(559): CodeIgniter\Config\BaseService::getSharedInstance('request', Object(Config\App))
16 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App))
17 SYSTEMPATH\Config\Services.php(539): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', [...])
18 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::createRequest(Object(Config\App))
19 SYSTEMPATH\CodeIgniter.php(656): CodeIgniter\Config\BaseService::__callStatic('createRequest', [...])
20 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->getRequestObject()
21 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-05-09 01:35:45 --> ErrorException: Uncaught CodeIgniter\Exceptions\ConfigException: Config\App::$baseURL "/" is not a valid URL. in C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\HTTP\SiteURI.php:199
Stack trace:
#0 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\HTTP\SiteURI.php(145): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
#1 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\HTTP\SiteURI.php(100): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), NULL, NULL)
#2 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\HTTP\SiteURIFactory.php(224): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), '/', NULL)
#3 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\HTTP\SiteURIFactory.php(45): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('/')
#4 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(805): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
#5 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(NULL, false)
#6 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#7 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(798): CodeIgniter\Config\BaseService::getSharedInstance('uri', NULL)
#8 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
#9 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(566): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#10 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
#11 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(524): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', Array)
#12 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request(NULL, false)
#13 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#14 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(520): CodeIgniter\Config\BaseService::getSharedInstance('request', NULL)
#15 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request()
#16 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Debug\Exceptions.php(150): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#17 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\ConfigException))
#18 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\ConfigException
Config\App::$baseURL "/" is not a valid URL.
#0 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\HTTP\SiteURI.php(145): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
#1 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\HTTP\SiteURI.php(100): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), NULL, NULL)
#2 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\HTTP\SiteURIFactory.php(224): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), '/', NULL)
#3 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\HTTP\SiteURIFactory.php(45): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('/')
#4 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(805): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
#5 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(NULL, false)
#6 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#7 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(798): CodeIgniter\Config\BaseService::getSharedInstance('uri', NULL)
#8 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
#9 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(566): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#10 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
#11 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(524): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', Array)
#12 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request(Object(Config\App), false)
#13 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#14 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(559): CodeIgniter\Config\BaseService::getSharedInstance('request', Object(Config\App))
#15 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App))
#16 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(539): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', Array)
#17 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::createRequest(Object(Config\App))
#18 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(656): CodeIgniter\Config\BaseService::__callStatic('createRequest', Array)
#19 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->getRequestObject()
#20 C:\xampp\htdocs\inventory_system\index.php(79): CodeIgniter\CodeIgniter->run()
#21 {main}
in SYSTEMPATH\HTTP\SiteURI.php on line 199.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2025-05-09 01:38:14 --> CodeIgniter\Exceptions\ConfigException: Config\App::$baseURL "/" is not a valid URL.
in SYSTEMPATH\HTTP\SiteURI.php on line 199.
 1 SYSTEMPATH\HTTP\SiteURI.php(145): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
 2 SYSTEMPATH\HTTP\SiteURI.php(100): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), null, null)
 3 SYSTEMPATH\HTTP\SiteURIFactory.php(224): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), '/', null)
 4 SYSTEMPATH\HTTP\SiteURIFactory.php(45): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('/')
 5 SYSTEMPATH\Config\Services.php(805): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
 6 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(null, false)
 7 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', [...])
 8 SYSTEMPATH\Config\Services.php(798): CodeIgniter\Config\BaseService::getSharedInstance('uri', null)
 9 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
10 SYSTEMPATH\Config\Services.php(566): CodeIgniter\Config\BaseService::__callStatic('uri', [])
11 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
12 SYSTEMPATH\Config\Services.php(524): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', [...])
13 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::request(Object(Config\App), false)
14 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', [...])
15 SYSTEMPATH\Config\Services.php(559): CodeIgniter\Config\BaseService::getSharedInstance('request', Object(Config\App))
16 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App))
17 SYSTEMPATH\Config\Services.php(539): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', [...])
18 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::createRequest(Object(Config\App))
19 SYSTEMPATH\CodeIgniter.php(656): CodeIgniter\Config\BaseService::__callStatic('createRequest', [...])
20 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->getRequestObject()
21 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-05-09 01:38:14 --> ErrorException: Uncaught CodeIgniter\Exceptions\ConfigException: Config\App::$baseURL "/" is not a valid URL. in C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\HTTP\SiteURI.php:199
Stack trace:
#0 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\HTTP\SiteURI.php(145): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
#1 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\HTTP\SiteURI.php(100): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), NULL, NULL)
#2 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\HTTP\SiteURIFactory.php(224): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), '/', NULL)
#3 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\HTTP\SiteURIFactory.php(45): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('/')
#4 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(805): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
#5 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(NULL, false)
#6 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#7 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(798): CodeIgniter\Config\BaseService::getSharedInstance('uri', NULL)
#8 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
#9 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(566): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#10 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
#11 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(524): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', Array)
#12 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request(NULL, false)
#13 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#14 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(520): CodeIgniter\Config\BaseService::getSharedInstance('request', NULL)
#15 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request()
#16 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Debug\Exceptions.php(150): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#17 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\ConfigException))
#18 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\ConfigException
Config\App::$baseURL "/" is not a valid URL.
#0 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\HTTP\SiteURI.php(145): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
#1 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\HTTP\SiteURI.php(100): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), NULL, NULL)
#2 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\HTTP\SiteURIFactory.php(224): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), '/', NULL)
#3 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\HTTP\SiteURIFactory.php(45): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('/')
#4 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(805): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
#5 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(NULL, false)
#6 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#7 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(798): CodeIgniter\Config\BaseService::getSharedInstance('uri', NULL)
#8 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
#9 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(566): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#10 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
#11 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(524): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', Array)
#12 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request(Object(Config\App), false)
#13 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#14 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(559): CodeIgniter\Config\BaseService::getSharedInstance('request', Object(Config\App))
#15 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App))
#16 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\Services.php(539): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', Array)
#17 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Config\BaseService.php(258): CodeIgniter\Config\Services::createRequest(Object(Config\App))
#18 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(656): CodeIgniter\Config\BaseService::__callStatic('createRequest', Array)
#19 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->getRequestObject()
#20 C:\xampp\htdocs\inventory_system\index.php(79): CodeIgniter\CodeIgniter->run()
#21 {main}
in SYSTEMPATH\HTTP\SiteURI.php on line 199.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2025-05-09 01:41:28 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'my_username'@'localhost' (using password: YES) in C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'my_username', 'my_password', 'my_database', 3306, '', 0)
#1 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(285): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\inventory_system\app\Controllers\Home.php(10): CodeIgniter\Database\MySQLi\Connection->getVersion()
#4 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(943): App\Controllers\Home->index()
#5 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\inventory_system\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(285): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\inventory_system\app\Controllers\Home.php(10): CodeIgniter\Database\MySQLi\Connection->getVersion()
#3 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(943): App\Controllers\Home->index()
#4 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\inventory_system\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-05-09 01:41:28 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(285): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Home.php(10): CodeIgniter\Database\MySQLi\Connection->getVersion()
 3 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Home->index()
 4 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-05-09 01:41:34 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'my_username'@'localhost' (using password: YES) in C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'my_username', 'my_password', 'my_database', 3306, '', 0)
#1 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(285): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\inventory_system\app\Controllers\Home.php(10): CodeIgniter\Database\MySQLi\Connection->getVersion()
#4 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(943): App\Controllers\Home->index()
#5 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\inventory_system\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(285): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\inventory_system\app\Controllers\Home.php(10): CodeIgniter\Database\MySQLi\Connection->getVersion()
#3 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(943): App\Controllers\Home->index()
#4 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\inventory_system\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-05-09 01:41:34 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(285): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Home.php(10): CodeIgniter\Database\MySQLi\Connection->getVersion()
 3 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Home->index()
 4 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-05-09 01:42:04 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'my_username'@'localhost' (using password: YES) in C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'my_username', 'my_password', 'my_database', 3306, '', 0)
#1 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(285): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\inventory_system\app\Controllers\Home.php(10): CodeIgniter\Database\MySQLi\Connection->getVersion()
#4 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(943): App\Controllers\Home->index()
#5 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\inventory_system\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(285): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\inventory_system\app\Controllers\Home.php(10): CodeIgniter\Database\MySQLi\Connection->getVersion()
#3 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(943): App\Controllers\Home->index()
#4 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\inventory_system\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-05-09 01:42:04 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(285): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Home.php(10): CodeIgniter\Database\MySQLi\Connection->getVersion()
 3 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Home->index()
 4 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-05-09 01:43:09 --> ErrorException: Constant expression contains invalid operations
in APPPATH\Config\Database.php on line 29.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2025-05-09 01:46:39 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'my_username'@'localhost' (using password: YES) in C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'my_username', 'my_password', 'my_database', '3306', '', 0)
#1 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(285): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\inventory_system\app\Controllers\Home.php(10): CodeIgniter\Database\MySQLi\Connection->getVersion()
#4 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(943): App\Controllers\Home->index()
#5 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\inventory_system\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(285): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\inventory_system\app\Controllers\Home.php(10): CodeIgniter\Database\MySQLi\Connection->getVersion()
#3 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(943): App\Controllers\Home->index()
#4 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\inventory_system\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-05-09 01:46:39 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(285): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Home.php(10): CodeIgniter\Database\MySQLi\Connection->getVersion()
 3 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Home->index()
 4 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-05-09 01:47:07 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', 'inventory_syste...', '', '3306', '', 0)
#1 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(285): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\inventory_system\app\Controllers\Home.php(10): CodeIgniter\Database\MySQLi\Connection->getVersion()
#4 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(943): App\Controllers\Home->index()
#5 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\inventory_system\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(285): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\inventory_system\app\Controllers\Home.php(10): CodeIgniter\Database\MySQLi\Connection->getVersion()
#3 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(943): App\Controllers\Home->index()
#4 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\inventory_system\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-05-09 01:47:07 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(285): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Home.php(10): CodeIgniter\Database\MySQLi\Connection->getVersion()
 3 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Home->index()
 4 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-05-09 01:52:07 --> mysqli_sql_exception: Invalid default value for 'created_at' in C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\Forge.php(555): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\xampp\htdocs\inventory_system\app\Database\Migrations\2025-05-09-014901_CreateUsersTable.php(53): CodeIgniter\Database\Forge->createTable('users')
#5 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(865): App\Database\Migrations\CreateUsersTable->up()
#6 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(181): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CLI\Console.php(46): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\inventory_system\spark(102): CodeIgniter\CLI\Console->run()
#11 {main}
ERROR - 2025-05-09 01:53:37 --> mysqli_sql_exception: Invalid default value for 'created_at' in C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\Forge.php(555): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\xampp\htdocs\inventory_system\app\Database\Migrations\2025-05-09-014901_CreateUsersTable.php(54): CodeIgniter\Database\Forge->createTable('users')
#5 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(865): App\Database\Migrations\CreateUsersTable->up()
#6 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(181): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CLI\Console.php(46): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\inventory_system\spark(102): CodeIgniter\CLI\Console->run()
#11 {main}
ERROR - 2025-05-09 01:54:18 --> mysqli_sql_exception: Invalid default value for 'created_at' in C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\Forge.php(555): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\xampp\htdocs\inventory_system\app\Database\Migrations\2025-05-09-014901_CreateUsersTable.php(54): CodeIgniter\Database\Forge->createTable('users')
#5 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(865): App\Database\Migrations\CreateUsersTable->up()
#6 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(181): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CLI\Console.php(46): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\inventory_system\spark(102): CodeIgniter\CLI\Console->run()
#11 {main}
ERROR - 2025-05-09 01:55:02 --> mysqli_sql_exception: Can't create table `inventory_system`.`users` (errno: 150 "Foreign key constraint is incorrectly formed") in C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\Forge.php(555): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\xampp\htdocs\inventory_system\app\Database\Migrations\2025-05-09-014901_CreateUsersTable.php(55): CodeIgniter\Database\Forge->createTable('users')
#5 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(865): App\Database\Migrations\CreateUsersTable->up()
#6 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(181): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CLI\Console.php(46): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\inventory_system\spark(102): CodeIgniter\CLI\Console->run()
#11 {main}
ERROR - 2025-05-09 01:56:06 --> mysqli_sql_exception: Can't create table `inventory_system`.`users` (errno: 150 "Foreign key constraint is incorrectly formed") in C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\Forge.php(555): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\xampp\htdocs\inventory_system\app\Database\Migrations\2025-05-09-014901_CreateUsersTable.php(55): CodeIgniter\Database\Forge->createTable('users')
#5 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(865): App\Database\Migrations\CreateUsersTable->up()
#6 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(181): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CLI\Console.php(46): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\inventory_system\spark(102): CodeIgniter\CLI\Console->run()
#11 {main}
ERROR - 2025-05-09 01:56:47 --> mysqli_sql_exception: Can't create table `inventory_system`.`users` (errno: 150 "Foreign key constraint is incorrectly formed") in C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\Forge.php(555): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\xampp\htdocs\inventory_system\app\Database\Migrations\2025-05-09-014901_CreateUsersTable.php(55): CodeIgniter\Database\Forge->createTable('users')
#5 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(865): App\Database\Migrations\CreateUsersTable->up()
#6 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(181): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CLI\Console.php(46): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\inventory_system\spark(102): CodeIgniter\CLI\Console->run()
#11 {main}
ERROR - 2025-05-09 01:56:48 --> mysqli_sql_exception: Can't create table `inventory_system`.`users` (errno: 150 "Foreign key constraint is incorrectly formed") in C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\Forge.php(555): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\xampp\htdocs\inventory_system\app\Database\Migrations\2025-05-09-014901_CreateUsersTable.php(55): CodeIgniter\Database\Forge->createTable('users')
#5 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(865): App\Database\Migrations\CreateUsersTable->up()
#6 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(181): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CLI\Console.php(46): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\inventory_system\spark(102): CodeIgniter\CLI\Console->run()
#11 {main}
ERROR - 2025-05-09 01:56:52 --> mysqli_sql_exception: Can't create table `inventory_system`.`users` (errno: 150 "Foreign key constraint is incorrectly formed") in C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\Forge.php(555): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\xampp\htdocs\inventory_system\app\Database\Migrations\2025-05-09-014901_CreateUsersTable.php(55): CodeIgniter\Database\Forge->createTable('users')
#5 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(865): App\Database\Migrations\CreateUsersTable->up()
#6 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(181): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CLI\Console.php(46): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\inventory_system\spark(102): CodeIgniter\CLI\Console->run()
#11 {main}
ERROR - 2025-05-09 01:57:36 --> mysqli_sql_exception: Can't create table `inventory_system`.`users` (errno: 150 "Foreign key constraint is incorrectly formed") in C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\Forge.php(555): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\xampp\htdocs\inventory_system\app\Database\Migrations\2025-05-09-014901_CreateUsersTable.php(55): CodeIgniter\Database\Forge->createTable('users')
#5 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(865): App\Database\Migrations\CreateUsersTable->up()
#6 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(181): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CLI\Console.php(46): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\inventory_system\spark(102): CodeIgniter\CLI\Console->run()
#11 {main}
ERROR - 2025-05-09 01:57:37 --> mysqli_sql_exception: Can't create table `inventory_system`.`users` (errno: 150 "Foreign key constraint is incorrectly formed") in C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\Forge.php(555): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\xampp\htdocs\inventory_system\app\Database\Migrations\2025-05-09-014901_CreateUsersTable.php(55): CodeIgniter\Database\Forge->createTable('users')
#5 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(865): App\Database\Migrations\CreateUsersTable->up()
#6 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(181): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CLI\Console.php(46): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\inventory_system\spark(102): CodeIgniter\CLI\Console->run()
#11 {main}
ERROR - 2025-05-09 01:58:10 --> mysqli_sql_exception: Can't create table `inventory_system`.`users` (errno: 150 "Foreign key constraint is incorrectly formed") in C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\Forge.php(555): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\xampp\htdocs\inventory_system\app\Database\Migrations\2025-05-09-014901_CreateUsersTable.php(55): CodeIgniter\Database\Forge->createTable('users')
#5 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(865): App\Database\Migrations\CreateUsersTable->up()
#6 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(181): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CLI\Console.php(46): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\inventory_system\spark(102): CodeIgniter\CLI\Console->run()
#11 {main}
ERROR - 2025-05-09 01:58:11 --> mysqli_sql_exception: Can't create table `inventory_system`.`users` (errno: 150 "Foreign key constraint is incorrectly formed") in C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\Forge.php(555): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\xampp\htdocs\inventory_system\app\Database\Migrations\2025-05-09-014901_CreateUsersTable.php(55): CodeIgniter\Database\Forge->createTable('users')
#5 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(865): App\Database\Migrations\CreateUsersTable->up()
#6 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(181): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CLI\Console.php(46): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\inventory_system\spark(102): CodeIgniter\CLI\Console->run()
#11 {main}
ERROR - 2025-05-09 01:58:19 --> mysqli_sql_exception: Can't create table `inventory_system`.`users` (errno: 150 "Foreign key constraint is incorrectly formed") in C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\Forge.php(555): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\xampp\htdocs\inventory_system\app\Database\Migrations\2025-05-09-014901_CreateUsersTable.php(55): CodeIgniter\Database\Forge->createTable('users')
#5 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(865): App\Database\Migrations\CreateUsersTable->up()
#6 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(181): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CLI\Console.php(46): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\inventory_system\spark(102): CodeIgniter\CLI\Console->run()
#11 {main}
ERROR - 2025-05-09 02:02:30 --> mysqli_sql_exception: Unknown column 'description' in 'field list' in C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `ro...', 0)
#1 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ro...')
#2 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ro...')
#3 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1803): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ro...', NULL, false)
#4 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2192): CodeIgniter\Database\BaseBuilder->batchExecute('_insertBatch', 100)
#5 C:\xampp\htdocs\inventory_system\app\Database\Seeds\RolesSeeder.php(27): CodeIgniter\Database\BaseBuilder->insertBatch(Array)
#6 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\Seeder.php(145): App\Database\Seeds\RolesSeeder->run()
#7 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Commands\Database\Seed.php(77): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#8 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Seed->run(Array)
#9 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CLI\Console.php(46): CodeIgniter\CLI\Commands->run('db:seed', Array)
#10 C:\xampp\htdocs\inventory_system\spark(102): CodeIgniter\CLI\Console->run()
#11 {main}
CRITICAL - 2025-05-09 02:08:03 --> ErrorException: Undefined variable $totalTime
in SYSTEMPATH\Debug\Toolbar\Views\toolbar.tpl.php on line 46.
 1 SYSTEMPATH\Debug\Toolbar\Views\toolbar.tpl.php(46): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $totalTime', 'C:\\xampp\\htdocs\\inventory_system\\vendor\\codeigniter4\\framework\\system\\Debug\\Toolbar\\Views\\toolbar.tpl.php', 46)
 2 SYSTEMPATH\Debug\Toolbar.php(512): include('C:\\xampp\\htdocs\\inventory_system\\vendor\\codeigniter4\\framework\\system\\Debug\\Toolbar\\Views\\toolbar.tpl.php')
 3 SYSTEMPATH\Debug\Toolbar.php(475): CodeIgniter\Debug\Toolbar->format([...], 'html')
 4 APPPATH\Config\Events.php(47): CodeIgniter\Debug\Toolbar->respond()
 5 SYSTEMPATH\Events\Events.php(154): CodeIgniter\Events\Events::Config\{closure}()
 6 SYSTEMPATH\CodeIgniter.php(442): CodeIgniter\Events\Events::trigger('pre_system')
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2025-05-09 02:08:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:09:34 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:11:51 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:11:51 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2025-05-09 02:11:51 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "login.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('login.php')
 2 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('login', [], true)
 3 APPPATH\Controllers\Auth.php(38): view('login')
 4 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Auth->login()
 5 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2025-05-09 02:13:58 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2025-05-09 02:13:58 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "login.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('login.php')
 2 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('login', [], true)
 3 APPPATH\Controllers\Auth.php(38): view('login')
 4 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Auth->login()
 5 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2025-05-09 02:14:00 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:14:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:14:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:14:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2025-05-09 02:14:32 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "login.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('login.php')
 2 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('login', [], true)
 3 APPPATH\Controllers\Auth.php(38): view('login')
 4 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Auth->login()
 5 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2025-05-09 02:15:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:15:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:16:03 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2025-05-09 02:16:03 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "login.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('login.php')
 2 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('login', [], true)
 3 APPPATH\Controllers\Auth.php(38): view('login')
 4 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Auth->login()
 5 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2025-05-09 02:17:19 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:17:34 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:18:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:18:36 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:18:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:18:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:19:04 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:19:09 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:19:09 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:19:15 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:19:15 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:19:52 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:19:53 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:19:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:19:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:19:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:20:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:20:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:20:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:20:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:25:15 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:25:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:29:06 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:29:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:29:38 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:29:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:29:44 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-05-09 02:35:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2025-05-09 02:45:52 --> ErrorException: Cannot declare class App\Database\Migrations\CreateInventoryHistoryTable, because the name is already in use
in APPPATH\Database\Migrations\2025-05-09-024500_CreateInventoryHistoryTable.php on line 7.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2025-05-09 02:48:37 --> mysqli_sql_exception: Can't create table `inventory_system`.`inventory_history_return` (errno: 150 "Foreign key constraint is incorrectly formed") in C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('CREATE TABLE `i...', 0)
#1 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `i...')
#2 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `i...')
#3 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\Forge.php(555): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `i...')
#4 C:\xampp\htdocs\inventory_system\app\Database\Migrations\2025-05-09-024826_CreateInventoryHistoryReturnTable.php(28): CodeIgniter\Database\Forge->createTable('inventory_histo...')
#5 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(865): App\Database\Migrations\CreateInventoryHistoryReturnTable->up()
#6 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(181): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\inventory_system\vendor\codeigniter4\framework\system\CLI\Console.php(46): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\inventory_system\spark(102): CodeIgniter\CLI\Console->run()
#11 {main}
